In [3]:
import pandas as pd
import os
from pathlib import Path

new_data = pd.read_csv("olist_sellers_dataset.csv")
new_data.head(10)

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP
5,c240c4061717ac1806ae6ee72be3533b,20920,rio de janeiro,RJ
6,e49c26c3edfa46d227d5121a6b6e4d37,55325,brejao,PE
7,1b938a7ec6ac5061a66a3766e0e75f90,16304,penapolis,SP
8,768a86e36ad6aae3d03ee3c6433d61df,1529,sao paulo,SP
9,ccc4bbb5f32a6ab2b7066a4130f114e3,80310,curitiba,PR

In [25]:
#from IPython.display import display, HTML

data_folder = Path("..")/"Data"

csv_files = list(data_folder.glob("*.csv"))

for i in csv_files:
    print(f"-- {i.name} --\n")
    print(pd.read_csv(i).info())

-- olist_customers_dataset.csv --

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  str
 1   customer_unique_id        99441 non-null  str
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  str
 4   customer_state            99441 non-null  str
dtypes: int64(1), str(4)
memory usage: 3.8 MB
None
-- olist_geolocation_dataset.csv --

<class 'pandas.DataFrame'>
RangeIndex: 1000163 entries, 0 to 1000162
Data columns (total 5 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   geolocation_zip_code_prefix  1000163 non-null  int64
 1   geolocation_lat              1000163 non-null  float64
 2   geolocation_lng              1000163 non-null  float64
 3   geolocation_city             1000163 non-null  str
 4   geolocation_state            1000163 non-null  str
dtypes: float64(2), int64(1), str(2)
memory usage: 38.2 MB
None
-- olist_orders_dataset.csv --

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  str
 1   customer_id                    99441 non-null  str
 2   order_status                   99441 non-null  str
 3   order_purchase_timestamp       99441 non-null  str
 4   order_approved_at              99281 non-null  str
 5   order_delivered_carrier_date   97658 non-null  str
 6   order_delivered_customer_date  96476 non-null  str
 7   order_estimated_delivery_date  99441 non-null  str
dtypes: str(8)
memory usage: 6.1 MB
None
-- olist_order_items_dataset.csv --

<class 'pandas.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  str
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  str
 3   seller_id            112650 non-null  str
 4   shipping_limit_date  112650 non-null  str
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), str(4)
memory usage: 6.0 MB
None
-- olist_order_payments_dataset.csv --

<class 'pandas.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  str
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  str
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), str(2)
memory usage: 4.0 MB
None
-- olist_order_reviews_dataset.csv --

<class 'pandas.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  str
 1   order_id                 99224 non-null  str
 2   review_score             99224 non-null  int64
 3   review_comment_title     11568 non-null  str
 4   review_comment_message   40977 non-null  str
 5   review_creation_date     99224 non-null  str
 6   review_answer_timestamp  99224 non-null  str
dtypes: int64(1), str(6)
memory usage: 5.3 MB
None
-- olist_products_dataset.csv --

<class 'pandas.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  str
 1   product_category_name       32341 non-null  str
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), str(2)
memory usage: 2.3 MB
None
-- olist_sellers_dataset.csv --

<class 'pandas.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   str
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3095 non-null   str
 3   seller_state            3095 non-null   str
dtypes: int64(1), str(3)
memory usage: 96.8 KB
None
-- product_category_name_translation.csv --

<class 'pandas.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 2 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   product_category_name          71 non-null     str
 1   product_category_name_english  71 non-null     str
dtypes: str(2)
memory usage: 1.2 KB
None

In [8]:
data_folder = Path("..")/"Data"

csv_files = list(data_folder.glob("*.csv"))
print(f"There are {len(csv_files)} data files")

df_dict = {}
for i in csv_files:
    df_dict[i.stem] = pd.read_csv(i)
    #df = pd.read_csv(i)
    #print(f"\n--{i.name}--")
    #print(df.shape)
    #print(df.columns.tolist())

There are 9 data files

In [35]:
date_columns = {
    "olist_orders_dataset": [
        "order_purchase_timestamp",
        "order_approved_at",
        "order_delivered_carrier_date",
        "order_delivered_customer_date",
        "order_estimated_delivery_date"
    ],
    "olist_order_reviews_dataset": [
        "review_creation_date",
        "review_answer_timestamp"
    ],
    "olist_order_items_dataset":[
        "shipping_limit_date"
    ]
}

for table, columns in date_columns.items():
    for col in columns:
        df_dict[table][col] = pd.to_datetime(df_dict[table][col], errors = "coerce")

In [34]:
df = "olist_order_reviews_dataset"

review_columns = {
    "review_comment_title": "No title",
    "review_comment_message": "No message"
}

new_dict = df_dict.copy()

for column, impute in review_columns.items():
    new_dict[df][column] = new_dict[df][column].fillna(impute)

    print(f"{df_dict[df][column].isna().sum()}\n")
    print(column)
    print(f"\n{new_dict[df][column].value_counts}\n")

0

review_comment_title

<bound method IndexOpsMixin.value_counts of 0        No title
1        No title
2        No title
3        No title
4        No title
           ...
99219    No title
99220    No title
99221    No title
99222    No title
99223    No title
Name: review_comment_title, Length: 99224, dtype: str>

0

review_comment_message

<bound method IndexOpsMixin.value_counts of 0                                               No message
1                                               No message
2                                               No message
3                    Recebi bem antes do prazo estipulado.
4        Parabéns lojas lannister adorei comprar pela I...
                               ...
99219                                           No message
99220                                           No message
99221    Excelente mochila, entrega super rápida. Super...
99222                                           No message
99223    meu produto chegou e ja tenho que devolver, po...
Name: review_comment_message, Length: 99224, dtype: str>

In [ ]:
for table, df in df_dict.items():
    df.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  str
 1   customer_unique_id        99441 non-null  str
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  str
 4   customer_state            99441 non-null  str
dtypes: int64(1), str(4)
memory usage: 3.8 MB
<class 'pandas.DataFrame'>
RangeIndex: 1000163 entries, 0 to 1000162
Data columns (total 5 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   geolocation_zip_code_prefix  1000163 non-null  int64
 1   geolocation_lat              1000163 non-null  float64
 2   geolocation_lng              1000163 non-null  float64
 3   geolocation_city             1000163 non-null  str
 4   geolocation_state            1000163 non-null  str
dtypes: float64(2), int64(1), str(2)
memory usage: 38.2 MB
<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  str
 1   customer_id                    99441 non-null  str
 2   order_status                   99441 non-null  str
 3   order_purchase_timestamp       99441 non-null  datetime64[us]
 4   order_approved_at              99281 non-null  datetime64[us]
 5   order_delivered_carrier_date   97658 non-null  datetime64[us]
 6   order_delivered_customer_date  96476 non-null  datetime64[us]
 7   order_estimated_delivery_date  99441 non-null  datetime64[us]
dtypes: datetime64[us](5), str(3)
memory usage: 6.1 MB
<class 'pandas.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  str
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  str
 3   seller_id            112650 non-null  str
 4   shipping_limit_date  112650 non-null  datetime64[us]
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: datetime64[us](1), float64(2), int64(1), str(3)
memory usage: 6.0 MB
<class 'pandas.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  str
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  str
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), str(2)
memory usage: 4.0 MB
<class 'pandas.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  str
 1   order_id                 99224 non-null  str
 2   review_score             99224 non-null  int64
 3   review_comment_title     11568 non-null  str
 4   review_comment_message   40977 non-null  str
 5   review_creation_date     99224 non-null  datetime64[us]
 6   review_answer_timestamp  99224 non-null  datetime64[us]
dtypes: datetime64[us](2), int64(1), str(4)
memory usage: 5.3 MB
<class 'pandas.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  str
 1   product_category_name       32341 non-null  str
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), str(2)
memory usage: 2.3 MB
<class 'pandas.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   str
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3095 non-null   str
 3   seller_state            3095 non-null   str
dtypes: int64(1), str(3)
memory usage: 96.8 KB
<class 'pandas.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 2 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   product_category_name          71 non-null     str
 1   product_category_name_english  71 non-null     str
dtypes: str(2)
memory usage: 1.2 KB

In [14]:
for name, df in df_dict.items():
    nulls = df.isna().sum()

    nulls = nulls[nulls>0].sort_values(ascending=False)
    print(f"\n-- {name} --")
    print(nulls)

-- olist_customers_dataset --
Series([], dtype: int64)

-- olist_geolocation_dataset --
Series([], dtype: int64)

-- olist_orders_dataset --
order_delivered_customer_date    2965
order_delivered_carrier_date     1783
order_approved_at                 160
dtype: int64

-- olist_order_items_dataset --
Series([], dtype: int64)

-- olist_order_payments_dataset --
Series([], dtype: int64)

-- olist_order_reviews_dataset --
review_comment_title      87656
review_comment_message    58247
dtype: int64

-- olist_products_dataset --
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

-- olist_sellers_dataset --
Series([], dtype: int64)

-- product_category_name_translation --
Series([], dtype: int64)

In [11]:
for name, df in df_dict:
    #print(df)
    print(f"\n{df_dict[df].sample(10)}")

ValueError: too many values to unpack (expected 2)

In [26]:
for df in df_dict:
    print(df)
    print(f"\n{df_dict[df].info()}")

olist_customers_dataset
<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  str
 1   customer_unique_id        99441 non-null  str
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  str
 4   customer_state            99441 non-null  str
dtypes: int64(1), str(4)
memory usage: 3.8 MB

None
olist_geolocation_dataset
<class 'pandas.DataFrame'>
RangeIndex: 1000163 entries, 0 to 1000162
Data columns (total 5 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   geolocation_zip_code_prefix  1000163 non-null  int64
 1   geolocation_lat              1000163 non-null  float64
 2   geolocation_lng              1000163 non-null  float64
 3   geolocation_city             1000163 non-null  str
 4   geolocation_state            1000163 non-null  str
dtypes: float64(2), int64(1), str(2)
memory usage: 38.2 MB

None
olist_orders_dataset
<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  str
 1   customer_id                    99441 non-null  str
 2   order_status                   99441 non-null  str
 3   order_purchase_timestamp       99441 non-null  str
 4   order_approved_at              99281 non-null  str
 5   order_delivered_carrier_date   97658 non-null  str
 6   order_delivered_customer_date  96476 non-null  str
 7   order_estimated_delivery_date  99441 non-null  str
dtypes: str(8)
memory usage: 6.1 MB

None
olist_order_items_dataset
<class 'pandas.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  str
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  str
 3   seller_id            112650 non-null  str
 4   shipping_limit_date  112650 non-null  str
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), str(4)
memory usage: 6.0 MB

None
olist_order_payments_dataset
<class 'pandas.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  str
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  str
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), str(2)
memory usage: 4.0 MB

None
olist_order_reviews_dataset
<class 'pandas.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  str
 1   order_id                 99224 non-null  str
 2   review_score             99224 non-null  int64
 3   review_comment_title     11568 non-null  str
 4   review_comment_message   40977 non-null  str
 5   review_creation_date     99224 non-null  str
 6   review_answer_timestamp  99224 non-null  str
dtypes: int64(1), str(6)
memory usage: 5.3 MB

None
olist_products_dataset
<class 'pandas.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  str
 1   product_category_name       32341 non-null  str
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), str(2)
memory usage: 2.3 MB

None
olist_sellers_dataset
<class 'pandas.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   str
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3095 non-null   str
 3   seller_state            3095 non-null   str
dtypes: int64(1), str(3)
memory usage: 96.8 KB

None
product_category_name_translation
<class 'pandas.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 2 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   product_category_name          71 non-null     str
 1   product_category_name_english  71 non-null     str
dtypes: str(2)
memory usage: 1.2 KB

None

In [19]:
#df_dict["olist_customers_dataset"]["customer_city"].value_counts()

df_dict["olist_orders_dataset"]["order_status"].value_counts()

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [ ]:
pd.DataFrame(sorted(df_dict["olist_customers_dataset"]["customer_city"].dropna().unique()), columns=["city"])

                     city
0     abadia dos dourados
1               abadiania
2                  abaete
3              abaetetuba
4                 abaiara
...                   ...
4114             xinguara
4115          xique-xique
4116             zacarias
4117              ze doca
4118               zortea

[4119 rows x 1 columns]

In [18]:
#pd.DataFrame(sorted(df_dict["olist_order_payments_dataset"]["payment_type"].dropna().unique()), columns=["Payment_type"])

df_dict["olist_order_payments_dataset"]["payment_type"].value_counts()

payment_type
credit_card    76795
boleto         19784
voucher         5775
debit_card      1529
not_defined        3
Name: count, dtype: int64

In [33]:
from IPython.display import display, HTML

cities = pd.DataFrame(
    sorted(df_dict["olist_customers_dataset"]["customer_city"].dropna().unique()),
    columns=["city"]
)

display(HTML(
    f'<div style="height:500px; overflow-y:auto;">{cities.to_html(index=False)}</div>'
))

In [27]:
for df in df_dict:
    print(df)
    print(f"\n{df_dict[df].describe()}")

olist_customers_dataset

       customer_zip_code_prefix
count              99441.000000
mean               35137.474583
std                29797.938996
min                 1003.000000
25%                11347.000000
50%                24416.000000
75%                58900.000000
max                99990.000000
olist_geolocation_dataset

       geolocation_zip_code_prefix  geolocation_lat  geolocation_lng
count                 1.000163e+06     1.000163e+06     1.000163e+06
mean                  3.657417e+04    -2.117615e+01    -4.639054e+01
std                   3.054934e+04     5.715866e+00     4.269748e+00
min                   1.001000e+03    -3.660537e+01    -1.014668e+02
25%                   1.107500e+04    -2.360355e+01    -4.857317e+01
50%                   2.653000e+04    -2.291938e+01    -4.663788e+01
75%                   6.350400e+04    -1.997962e+01    -4.376771e+01
max                   9.999000e+04     4.506593e+01     1.211054e+02
olist_orders_dataset

                                order_id                       customer_id  \
count                              99441                             99441
unique                             99441                             99441
top     e481f51cbdc54678b7cc49136f2d6af7  9ef432eb6251297304e76186b10a928d
freq                                   1                                 1

       order_status order_purchase_timestamp    order_approved_at  \
count         99441                    99441                99281
unique            8                    98875                90733
top       delivered      2018-03-31 15:08:21  2018-02-27 04:31:10
freq          96478                        3                    9

       order_delivered_carrier_date order_delivered_customer_date  \
count                         97658                         96476
unique                        81018                         95664
top             2018-05-09 15:48:00           2018-05-14 20:02:44
freq                             47                             3

       order_estimated_delivery_date
count                          99441
unique                           459
top              2017-12-20 00:00:00
freq                             522
olist_order_items_dataset

       order_item_id          price  freight_value
count  112650.000000  112650.000000  112650.000000
mean        1.197834     120.653739      19.990320
std         0.705124     183.633928      15.806405
min         1.000000       0.850000       0.000000
25%         1.000000      39.900000      13.080000
50%         1.000000      74.990000      16.260000
75%         1.000000     134.900000      21.150000
max        21.000000    6735.000000     409.680000
olist_order_payments_dataset

       payment_sequential  payment_installments  payment_value
count       103886.000000         103886.000000  103886.000000
mean             1.092679              2.853349     154.100380
std              0.706584              2.687051     217.494064
min              1.000000              0.000000       0.000000
25%              1.000000              1.000000      56.790000
50%              1.000000              1.000000     100.000000
75%              1.000000              4.000000     171.837500
max             29.000000             24.000000   13664.080000
olist_order_reviews_dataset

       review_score
count  99224.000000
mean       4.086421
std        1.347579
min        1.000000
25%        4.000000
50%        5.000000
75%        5.000000
max        5.000000
olist_products_dataset

       product_name_lenght  product_description_lenght  product_photos_qty  \
count         32341.000000                32341.000000        32341.000000
mean             48.476949                  771.495285            2.188986
std              10.245741                  635.115225            1.736766
min               5.000000                    4.000000            1.000000
25%              42.000000                  339.000000            1.000000
50%              51.000000                  595.000000            1.000000
75%              57.000000                  972.000000            3.000000
max              76.000000                 3992.000000           20.000000

       product_weight_g  product_length_cm  product_height_cm  \
count      32949.000000       32949.000000       32949.000000
mean        2276.472488          30.815078          16.937661
std         4282.038731          16.914458          13.637554
min            0.000000           7.000000           2.000000
25%          300.000000          18.000000           8.000000
50%          700.000000          25.000000          13.000000
75%         1900.000000          38.000000          21.000000
max        40425.000000         105.000000         105.000000

       product_width_cm
count      32949.000000
mean          23.196728
std           12.079047
min            6.000000
25%           15.000000
50%           20.000000
75%           30.000000
max          118.000000
olist_sellers_dataset

       seller_zip_code_prefix
count             3095.000000
mean             32291.059451
std              32713.453830
min               1001.000000
25%               7093.500000
50%              14940.000000
75%              64552.500000
max              99730.000000
product_category_name_translation

       product_category_name product_category_name_english
count                     71                            71
unique                    71                            71
top             beleza_saude                 health_beauty
freq                       1                             1

In [120]:
from rapidfuzz import fuzz, process

print(fuzz.ratio("hello", "hallo"))

80.0

In [51]:
fuzz.partial_ratio("hello_world","hallo")

fuzz.partial_ratio_alignment("why_hello_world!","hello_world")

fuzz.token_set_ratio("world hello","hello world")

fuzz.partial_token_set_ratio("hello world and universe", "hello world")

100.0

In [111]:
#fuzz.partial_ratio_alignment("why hello and world!","hello_world")

fuzz.partial_token_set_ratio("why hello and world!","hello world")

fuzz.partial_token_set_ratio("why world and hello!","hello and world why")

fuzz.token_sort_ratio("why world and hello!","hello and world why")

fuzz.partial_ratio("hello world","world hello me")

fuzz.partial_token_set_ratio("hello world","world hello me")

fuzz.partial_token_set_ratio("why world and hallo!","hello and world why")

fuzz.partial_token_set_ratio("hello world", "hallo worldme")

fuzz.ratio("uncle", "uncla henry",)

62.5

In [119]:
fuzz.token_ratio("alagoinha abua","abua alagoinhas")

96.55172413793103

In [50]:
fuzz.WRatio("hello", "hello world")

fuzz.QRatio("hello", "hallo")

80.0

In [121]:
similarities_dict = {}
for item in df_dict["olist_customers_dataset"]["customer_city"]:
    result = process.extract(item, df_dict["olist_customers_dataset"]["customer_city"],scorer=fuzz.ratio)
    similarities_dict[item] = result

KeyboardInterrupt:

In [149]:
cities = sorted(
    df_dict["olist_customers_dataset"]["customer_city"]
    .dropna()
    .unique()
)

#similarities_dict_2 = {}
similarities_list = []
for item in cities:
    results = process.extract(item, cities, score_cutoff=90,scorer=fuzz.ratio, limit = 5)
    similarities_dict[item] = result
    #similarities_list = []
    #similarities_list.append()
    for city, score, _ in results:
        if item != city:
            similarities_list.append((item, city,score))
            #similarities_dict_2[item] = similarities_list

In [151]:
#similarities_dict_2
similarities_df = pd.DataFrame(similarities_list, columns=["city", "possible_match", "similarity"]
).sort_values("similarity", ascending=False)

similarities_df

display(HTML(
    f'<div style="height:500px; overflow-y:auto;">{similarities_df.to_html(index=False)}</div>'
))

In [126]:
similarities_dict

{'franca': [('franca', 100.0, 0),
  ('franca', 100.0, 241),
  ('franca', 100.0, 650),
  ('franca', 100.0, 700),
  ('franca', 100.0, 1894)],
 'sao bernardo do campo': [('sao bernardo do campo', 100.0, 1),
  ('sao bernardo do campo', 100.0, 88),
  ('sao bernardo do campo', 100.0, 130),
  ('sao bernardo do campo', 100.0, 143),
  ('sao bernardo do campo', 100.0, 350)],
 'sao paulo': [('sao paulo', 100.0, 2),
  ('sao paulo', 100.0, 6),
  ('sao paulo', 100.0, 13),
  ('sao paulo', 100.0, 18),
  ('sao paulo', 100.0, 22)],
 'mogi das cruzes': [('mogi das cruzes', 100.0, 3),
  ('mogi das cruzes', 100.0, 105),
  ('mogi das cruzes', 100.0, 914),
  ('mogi das cruzes', 100.0, 1153),
  ('mogi das cruzes', 100.0, 1275)],
 'campinas': [('campinas', 100.0, 4),
  ('campinas', 100.0, 188),
  ('campinas', 100.0, 232),
  ('campinas', 100.0, 332),
  ('campinas', 100.0, 508)],
 'jaragua do sul': [('jaragua do sul', 100.0, 5),
  ('jaragua do sul', 100.0, 49),
  ('jaragua do sul', 100.0, 102),
  ('jaragua do sul', 100.0, 1311),
  ('jaragua do sul', 100.0, 2392)],
 'timoteo': [('timoteo', 100.0, 7),
  ('timoteo', 100.0, 1809),
  ('timoteo', 100.0, 3860),
  ('timoteo', 100.0, 5106),
  ('timoteo', 100.0, 6139)],
 'curitiba': [('curitiba', 100.0, 8),
  ('curitiba', 100.0, 23),
  ('curitiba', 100.0, 34),
  ('curitiba', 100.0, 117),
  ('curitiba', 100.0, 459)],
 'belo horizonte': [('belo horizonte', 100.0, 9),
  ('belo horizonte', 100.0, 45),
  ('belo horizonte', 100.0, 66),
  ('belo horizonte', 100.0, 118),
  ('belo horizonte', 100.0, 129)],
 'montes claros': [('montes claros', 100.0, 10),
  ('montes claros', 100.0, 51),
  ('montes claros', 100.0, 392),
  ('montes claros', 100.0, 712),
  ('montes claros', 100.0, 798)],
 'rio de janeiro': [('rio de janeiro', 100.0, 11),
  ('rio de janeiro', 100.0, 16),
  ('rio de janeiro', 100.0, 53),
  ('rio de janeiro', 100.0, 64),
  ('rio de janeiro', 100.0, 154)],
 'lencois paulista': [('lencois paulista', 100.0, 12),
  ('lencois paulista', 100.0, 2386),
  ('lencois paulista', 100.0, 5732),
  ('lencois paulista', 100.0, 8057),
  ('lencois paulista', 100.0, 11744)],
 'caxias do sul': [('caxias do sul', 100.0, 14),
  ('caxias do sul', 100.0, 216),
  ('caxias do sul', 100.0, 229),
  ('caxias do sul', 100.0, 574),
  ('caxias do sul', 100.0, 667)],
 'piracicaba': [('piracicaba', 100.0, 15),
  ('piracicaba', 100.0, 322),
  ('piracicaba', 100.0, 513),
  ('piracicaba', 100.0, 519),
  ('piracicaba', 100.0, 716)],
 'guarulhos': [('guarulhos', 100.0, 17),
  ('guarulhos', 100.0, 36),
  ('guarulhos', 100.0, 40),
  ('guarulhos', 100.0, 43),
  ('guarulhos', 100.0, 133)],
 'pacaja': [('pacaja', 100.0, 19),
  ('pacaja', 100.0, 12352),
  ('pacaja', 100.0, 34782),
  ('pacaja', 100.0, 39694),
  ('pacaja', 100.0, 85618)],
 'florianopolis': [('florianopolis', 100.0, 20),
  ('florianopolis', 100.0, 493),
  ('florianopolis', 100.0, 516),
  ('florianopolis', 100.0, 571),
  ('florianopolis', 100.0, 614)],
 'aparecida de goiania': [('aparecida de goiania', 100.0, 21),
  ('aparecida de goiania', 100.0, 363),
  ('aparecida de goiania', 100.0, 790),
  ('aparecida de goiania', 100.0, 841),
  ('aparecida de goiania', 100.0, 867)],
 'santo andre': [('santo andre', 100.0, 25),
  ('santo andre', 100.0, 185),
  ('santo andre', 100.0, 194),
  ('santo andre', 100.0, 331),
  ('santo andre', 100.0, 456)],
 'goiania': [('goiania', 100.0, 26),
  ('goiania', 100.0, 270),
  ('goiania', 100.0, 325),
  ('goiania', 100.0, 369),
  ('goiania', 100.0, 413)],
 'cachoeiro de itapemirim': [('cachoeiro de itapemirim', 100.0, 28),
  ('cachoeiro de itapemirim', 100.0, 68),
  ('cachoeiro de itapemirim', 100.0, 655),
  ('cachoeiro de itapemirim', 100.0, 1658),
  ('cachoeiro de itapemirim', 100.0, 1895)],
 'sao jose dos campos': [('sao jose dos campos', 100.0, 30),
  ('sao jose dos campos', 100.0, 186),
  ('sao jose dos campos', 100.0, 263),
  ('sao jose dos campos', 100.0, 389),
  ('sao jose dos campos', 100.0, 479)],
 'sao roque': [('sao roque', 100.0, 31),
  ('sao roque', 100.0, 794),
  ('sao roque', 100.0, 907),
  ('sao roque', 100.0, 1888),
  ('sao roque', 100.0, 5634)],
 'camacari': [('camacari', 100.0, 32),
  ('camacari', 100.0, 4312),
  ('camacari', 100.0, 4666),
  ('camacari', 100.0, 5955),
  ('camacari', 100.0, 10356)],
 'resende': [('resende', 100.0, 33),
  ('resende', 100.0, 1357),
  ('resende', 100.0, 1385),
  ('resende', 100.0, 1874),
  ('resende', 100.0, 2522)],
 'sumare': [('sumare', 100.0, 35),
  ('sumare', 100.0, 367),
  ('sumare', 100.0, 1661),
  ('sumare', 100.0, 2917),
  ('sumare', 100.0, 3070)],
 'novo hamburgo': [('novo hamburgo', 100.0, 37),
  ('novo hamburgo', 100.0, 1192),
  ('novo hamburgo', 100.0, 1366),
  ('novo hamburgo', 100.0, 3490),
  ('novo hamburgo', 100.0, 6041)],
 'sao luis': [('sao luis', 100.0, 38),
  ('sao luis', 100.0, 99),
  ('sao luis', 100.0, 833),
  ('sao luis', 100.0, 1058),
  ('sao luis', 100.0, 1170)],
 'sao jose': [('sao jose', 100.0, 39),
  ('sao jose', 100.0, 371),
  ('sao jose', 100.0, 461),
  ('sao jose', 100.0, 1935),
  ('sao jose', 100.0, 2635)],
 'santa barbara': [('santa barbara', 100.0, 41),
  ('santa barbara', 100.0, 1732),
  ('santa barbara', 100.0, 2738),
  ('santa barbara', 100.0, 3075),
  ('santa barbara', 100.0, 4190)],
 'ribeirao preto': [('ribeirao preto', 100.0, 44),
  ('ribeirao preto', 100.0, 406),
  ('ribeirao preto', 100.0, 420),
  ('ribeirao preto', 100.0, 510),
  ('ribeirao preto', 100.0, 881)],
 'ituiutaba': [('ituiutaba', 100.0, 46),
  ('ituiutaba', 100.0, 7012),
  ('ituiutaba', 100.0, 9784),
  ('ituiutaba', 100.0, 12164),
  ('ituiutaba', 100.0, 16824)],
 'taquarituba': [('taquarituba', 100.0, 47),
  ('taquarituba', 100.0, 4956),
  ('taquarituba', 100.0, 10966),
  ('taquarituba', 100.0, 16113),
  ('taquarituba', 100.0, 24657)],
 'sao jose dos pinhais': [('sao jose dos pinhais', 100.0, 48),
  ('sao jose dos pinhais', 100.0, 1386),
  ('sao jose dos pinhais', 100.0, 4310),
  ('sao jose dos pinhais', 100.0, 5204),
  ('sao jose dos pinhais', 100.0, 6360)],
 'barrinha': [('barrinha', 100.0, 52),
  ('barrinha', 100.0, 4232),
  ('barrinha', 100.0, 5690),
  ('barrinha', 100.0, 7654),
  ('barrinha', 100.0, 9262)],
 'parati': [('parati', 100.0, 54),
  ('parati', 100.0, 4147),
  ('parati', 100.0, 8388),
  ('parati', 100.0, 13467),
  ('parati', 100.0, 16014)],
 'dourados': [('dourados', 100.0, 55),
  ('dourados', 100.0, 278),
  ('dourados', 100.0, 4277),
  ('dourados', 100.0, 5770),
  ('dourados', 100.0, 7135)],
 'trindade': [('trindade', 100.0, 57),
  ('trindade', 100.0, 1976),
  ('trindade', 100.0, 2659),
  ('trindade', 100.0, 11012),
  ('trindade', 100.0, 15316)],
 'cascavel': [('cascavel', 100.0, 58),
  ('cascavel', 100.0, 1127),
  ('cascavel', 100.0, 2490),
  ('cascavel', 100.0, 2664),
  ('cascavel', 100.0, 4153)],
 'fortaleza': [('fortaleza', 100.0, 59),
  ('fortaleza', 100.0, 70),
  ('fortaleza', 100.0, 303),
  ('fortaleza', 100.0, 422),
  ('fortaleza', 100.0, 546)],
 'brasilia': [('brasilia', 100.0, 60),
  ('brasilia', 100.0, 94),
  ('brasilia', 100.0, 106),
  ('brasilia', 100.0, 138),
  ('brasilia', 100.0, 144)],
 'pelotas': [('pelotas', 100.0, 62),
  ('pelotas', 100.0, 2179),
  ('pelotas', 100.0, 2420),
  ('pelotas', 100.0, 2549),
  ('pelotas', 100.0, 2576)],
 'porto alegre': [('porto alegre', 100.0, 63),
  ('porto alegre', 100.0, 87),
  ('porto alegre', 100.0, 126),
  ('porto alegre', 100.0, 238),
  ('porto alegre', 100.0, 244)],
 'salto': [('salto', 100.0, 65),
  ('salto', 100.0, 89),
  ('salto', 100.0, 1007),
  ('salto', 100.0, 1930),
  ('salto', 100.0, 3895)],
 'jundiai': [('jundiai', 100.0, 67),
  ('jundiai', 100.0, 183),
  ('jundiai', 100.0, 252),
  ('jundiai', 100.0, 416),
  ('jundiai', 100.0, 843)],
 'cacapava': [('cacapava', 100.0, 69),
  ('cacapava', 100.0, 251),
  ('cacapava', 100.0, 597),
  ('cacapava', 100.0, 629),
  ('cacapava', 100.0, 988)],
 'sao vicente': [('sao vicente', 100.0, 71),
  ('sao vicente', 100.0, 78),
  ('sao vicente', 100.0, 374),
  ('sao vicente', 100.0, 721),
  ('sao vicente', 100.0, 1015)],
 'uberlandia': [('uberlandia', 100.0, 72),
  ('uberlandia', 100.0, 124),
  ('uberlandia', 100.0, 217),
  ('uberlandia', 100.0, 359),
  ('uberlandia', 100.0, 434)],
 'botelhos': [('botelhos', 100.0, 73),
  ('botelhos', 100.0, 2567),
  ('botelhos', 100.0, 2992),
  ('botelhos', 100.0, 3118),
  ('botelhos', 100.0, 41409)],
 'sao goncalo': [('sao goncalo', 100.0, 74),
  ('sao goncalo', 100.0, 131),
  ('sao goncalo', 100.0, 407),
  ('sao goncalo', 100.0, 542),
  ('sao goncalo', 100.0, 561)],
 'araucaria': [('araucaria', 100.0, 77),
  ('araucaria', 100.0, 1934),
  ('araucaria', 100.0, 3491),
  ('araucaria', 100.0, 4158),
  ('araucaria', 100.0, 6019)],
 'nova iguacu': [('nova iguacu', 100.0, 79),
  ('nova iguacu', 100.0, 544),
  ('nova iguacu', 100.0, 564),
  ('nova iguacu', 100.0, 653),
  ('nova iguacu', 100.0, 664)],
 'areia branca': [('areia branca', 100.0, 81),
  ('areia branca', 100.0, 42594),
  ('areia branca', 100.0, 67872),
  ('aguia branca', 83.33333333333334, 66713),
  ('aguia branca', 83.33333333333334, 90396)],
 'campos dos goytacazes': [('campos dos goytacazes', 100.0, 83),
  ('campos dos goytacazes', 100.0, 607),
  ('campos dos goytacazes', 100.0, 1043),
  ('campos dos goytacazes', 100.0, 1215),
  ('campos dos goytacazes', 100.0, 1217)],
 'sao carlos': [('sao carlos', 100.0, 84),
  ('sao carlos', 100.0, 95),
  ('sao carlos', 100.0, 1631),
  ('sao carlos', 100.0, 1635),
  ('sao carlos', 100.0, 1883)],
 'itajuba': [('itajuba', 100.0, 86),
  ('itajuba', 100.0, 768),
  ('itajuba', 100.0, 949),
  ('itajuba', 100.0, 2324),
  ('itajuba', 100.0, 4944)],
 'cruz das almas': [('cruz das almas', 100.0, 90),
  ('cruz das almas', 100.0, 1291),
  ('cruz das almas', 100.0, 3792),
  ('cruz das almas', 100.0, 6244),
  ('cruz das almas', 100.0, 8460)],
 'vassouras': [('vassouras', 100.0, 91),
  ('vassouras', 100.0, 4374),
  ('vassouras', 100.0, 8854),
  ('vassouras', 100.0, 10259),
  ('vassouras', 100.0, 13340)],
 'feira de santana': [('feira de santana', 100.0, 92),
  ('feira de santana', 100.0, 1205),
  ('feira de santana', 100.0, 1274),
  ('feira de santana', 100.0, 1298),
  ('feira de santana', 100.0, 1495)],
 'niteroi': [('niteroi', 100.0, 98),
  ('niteroi', 100.0, 243),
  ('niteroi', 100.0, 296),
  ('niteroi', 100.0, 395),
  ('niteroi', 100.0, 410)],
 'sobral': [('sobral', 100.0, 103),
  ('sobral', 100.0, 1072),
  ('sobral', 100.0, 4011),
  ('sobral', 100.0, 6190),
  ('sobral', 100.0, 8095)],
 'divinopolis': [('divinopolis', 100.0, 104),
  ('divinopolis', 100.0, 511),
  ('divinopolis', 100.0, 773),
  ('divinopolis', 100.0, 1564),
  ('divinopolis', 100.0, 2170)],
 'paraiba do sul': [('paraiba do sul', 100.0, 109),
  ('paraiba do sul', 100.0, 6655),
  ('paraiba do sul', 100.0, 9960),
  ('paraiba do sul', 100.0, 18992),
  ('paraiba do sul', 100.0, 19015)],
 'paulista': [('paulista', 100.0, 110),
  ('paulista', 100.0, 4513),
  ('paulista', 100.0, 5915),
  ('paulista', 100.0, 6593),
  ('paulista', 100.0, 9234)],
 'carapicuiba': [('carapicuiba', 100.0, 112),
  ('carapicuiba', 100.0, 360),
  ('carapicuiba', 100.0, 801),
  ('carapicuiba', 100.0, 1138),
  ('carapicuiba', 100.0, 1469)],
 'bom principio': [('bom principio', 100.0, 114),
  ('bom principio', 100.0, 14318),
  ('bom principio', 100.0, 21266),
  ('bom principio', 100.0, 48698),
  ('bom principio', 100.0, 49041)],
 'astolfo dutra': [('astolfo dutra', 100.0, 116),
  ('astolfo dutra', 100.0, 1169),
  ('astolfo dutra', 100.0, 19981),
  ('astolfo dutra', 100.0, 21848),
  ('astolfo dutra', 100.0, 34028)],
 'marialva': [('marialva', 100.0, 119),
  ('marialva', 100.0, 1393),
  ('marialva', 100.0, 17551),
  ('marialva', 100.0, 30730),
  ('marialva', 100.0, 34086)],
 'sao jose do rio preto': [('sao jose do rio preto', 100.0, 121),
  ('sao jose do rio preto', 100.0, 164),
  ('sao jose do rio preto', 100.0, 180),
  ('sao jose do rio preto', 100.0, 639),
  ('sao jose do rio preto', 100.0, 1193)],
 'cabo frio': [('cabo frio', 100.0, 122),
  ('cabo frio', 100.0, 891),
  ('cabo frio', 100.0, 1793),
  ('cabo frio', 100.0, 2398),
  ('cabo frio', 100.0, 3419)],
 'contagem': [('contagem', 100.0, 123),
  ('contagem', 100.0, 151),
  ('contagem', 100.0, 378),
  ('contagem', 100.0, 454),
  ('contagem', 100.0, 573)],
 'cafeara': [('cafeara', 100.0, 125),
  ('cafeara', 100.0, 84169),
  ('cafeara', 100.0, 84450)],
 'sao joaquim da barra': [('sao joaquim da barra', 100.0, 127),
  ('sao joaquim da barra', 100.0, 1210),
  ('sao joaquim da barra', 100.0, 1259),
  ('sao joaquim da barra', 100.0, 5036),
  ('sao joaquim da barra', 100.0, 9704)],
 'foz do iguacu': [('foz do iguacu', 100.0, 128),
  ('foz do iguacu', 100.0, 1704),
  ('foz do iguacu', 100.0, 1912),
  ('foz do iguacu', 100.0, 2617),
  ('foz do iguacu', 100.0, 4469)],
 'suzano': [('suzano', 100.0, 132),
  ('suzano', 100.0, 593),
  ('suzano', 100.0, 679),
  ('suzano', 100.0, 1159),
  ('suzano', 100.0, 1178)],
 'timbo': [('timbo', 100.0, 134),
  ('timbo', 100.0, 7045),
  ('timbo', 100.0, 15377),
  ('timbo', 100.0, 23652),
  ('timbo', 100.0, 27688)],
 'camboriu': [('camboriu', 100.0, 135),
  ('camboriu', 100.0, 3308),
  ('camboriu', 100.0, 4990),
  ('camboriu', 100.0, 8005),
  ('camboriu', 100.0, 9387)],
 'nova bassano': [('nova bassano', 100.0, 136),
  ('nova bassano', 100.0, 10343),
  ('nova bassano', 100.0, 62089),
  ('nova bassano', 100.0, 97140)],
 'rio grande': [('rio grande', 100.0, 137),
  ('rio grande', 100.0, 666),
  ('rio grande', 100.0, 1617),
  ('rio grande', 100.0, 2142),
  ('rio grande', 100.0, 2289)],
 'braganca paulista': [('braganca paulista', 100.0, 139),
  ('braganca paulista', 100.0, 283),
  ('braganca paulista', 100.0, 1276),
  ('braganca paulista', 100.0, 1945),
  ('braganca paulista', 100.0, 2067)],
 'barra do garcas': [('barra do garcas', 100.0, 140),
  ('barra do garcas', 100.0, 2944),
  ('barra do garcas', 100.0, 3117),
  ('barra do garcas', 100.0, 5035),
  ('barra do garcas', 100.0, 19679)],
 'embu': [('embu', 100.0, 142),
  ('embu', 100.0, 19697),
  ('embu', 100.0, 41429),
  ('embu', 100.0, 45157),
  ('embu', 100.0, 55319)],
 'urussanga': [('urussanga', 100.0, 145),
  ('urussanga', 100.0, 25673),
  ('urussanga', 100.0, 26822),
  ('urussanga', 100.0, 28413),
  ('urussanga', 100.0, 40863)],
 'silvianopolis': [('silvianopolis', 100.0, 146),
  ('silvianopolis', 100.0, 33157),
  ('silvianopolis', 100.0, 77760),
  ('silvanopolis', 96.0, 61504),
  ('vianopolis', 86.95652173913044, 554)],
 'gameleiras': [('gameleiras', 100.0, 148),
  ('gameleiras', 100.0, 83568),
  ('gameleiras', 100.0, 85573),
  ('gameleira', 94.73684210526316, 24959),
  ('gameleira', 94.73684210526316, 39892)],
 'belem': [('belem', 100.0, 149),
  ('belem', 100.0, 179),
  ('belem', 100.0, 987),
  ('belem', 100.0, 1033),
  ('belem', 100.0, 1266)],
 'pocos de caldas': [('pocos de caldas', 100.0, 150),
  ('pocos de caldas', 100.0, 3353),
  ('pocos de caldas', 100.0, 3449),
  ('pocos de caldas', 100.0, 3657),
  ('pocos de caldas', 100.0, 5365)],
 'santos': [('santos', 100.0, 152),
  ('santos', 100.0, 155),
  ('santos', 100.0, 365),
  ('santos', 100.0, 429),
  ('santos', 100.0, 745)],
 'piracaia': [('piracaia', 100.0, 153),
  ('piracaia', 100.0, 3761),
  ('piracaia', 100.0, 3796),
  ('piracaia', 100.0, 4756),
  ('piracaia', 100.0, 25055)],
 'sinop': [('sinop', 100.0, 156),
  ('sinop', 100.0, 1742),
  ('sinop', 100.0, 2037),
  ('sinop', 100.0, 2990),
  ('sinop', 100.0, 3568)],
 'guaruja': [('guaruja', 100.0, 157),
  ('guaruja', 100.0, 329),
  ('guaruja', 100.0, 543),
  ('guaruja', 100.0, 1718),
  ('guaruja', 100.0, 1770)],
 'barueri': [('barueri', 100.0, 158),
  ('barueri', 100.0, 482),
  ('barueri', 100.0, 565),
  ('barueri', 100.0, 690),
  ('barueri', 100.0, 1093)],
 'feliz': [('feliz', 100.0, 160),
  ('feliz', 100.0, 5028),
  ('feliz', 100.0, 17347),
  ('feliz', 100.0, 19007),
  ('feliz', 100.0, 19260)],
 'jambeiro': [('jambeiro', 100.0, 163),
  ('jambeiro', 100.0, 59289),
  ('jambeiro', 100.0, 64289),
  ('jambeiro', 100.0, 85318)],
 'ipatinga': [('ipatinga', 100.0, 165),
  ('ipatinga', 100.0, 257),
  ('ipatinga', 100.0, 418),
  ('ipatinga', 100.0, 942),
  ('ipatinga', 100.0, 996)],
 'tupa': [('tupa', 100.0, 166),
  ('tupa', 100.0, 1258),
  ('tupa', 100.0, 3196),
  ('tupa', 100.0, 5631),
  ('tupa', 100.0, 6767)],
 'blumenau': [('blumenau', 100.0, 169),
  ('blumenau', 100.0, 2218),
  ('blumenau', 100.0, 2254),
  ('blumenau', 100.0, 2286),
  ('blumenau', 100.0, 2374)],
 'moncoes': [('moncoes', 100.0, 170), ('moncoes', 100.0, 16747)],
 'balneario camboriu': [('balneario camboriu', 100.0, 173),
  ('balneario camboriu', 100.0, 1967),
  ('balneario camboriu', 100.0, 2573),
  ('balneario camboriu', 100.0, 3498),
  ('balneario camboriu', 100.0, 5473)],
 'vargem grande': [('vargem grande', 100.0, 176),
  ('varzea grande', 84.61538461538461, 3185),
  ('varzea grande', 84.61538461538461, 4592),
  ('varzea grande', 84.61538461538461, 5923),
  ('varzea grande', 84.61538461538461, 7510)],
 'rio brilhante': [('rio brilhante', 100.0, 177),
  ('rio brilhante', 100.0, 520),
  ('rio brilhante', 100.0, 5188),
  ('rio brilhante', 100.0, 6164),
  ('rio brilhante', 100.0, 20442)],
 'eugenopolis': [('eugenopolis', 100.0, 178),
  ('eugenopolis', 100.0, 54745),
  ('eugenopolis', 100.0, 69224),
  ('eugenopolis', 100.0, 71107),
  ('eugenopolis', 100.0, 80629)],
 'paulinia': [('paulinia', 100.0, 181),
  ('paulinia', 100.0, 625),
  ('paulinia', 100.0, 1833),
  ('paulinia', 100.0, 2769),
  ('paulinia', 100.0, 3134)],
 'apucarana': [('apucarana', 100.0, 190),
  ('apucarana', 100.0, 5118),
  ('apucarana', 100.0, 6744),
  ('apucarana', 100.0, 7736),
  ('apucarana', 100.0, 9002)],
 'recife': [('recife', 100.0, 191),
  ('recife', 100.0, 509),
  ('recife', 100.0, 582),
  ('recife', 100.0, 601),
  ('recife', 100.0, 719)],
 'osasco': [('osasco', 100.0, 192),
  ('osasco', 100.0, 442),
  ('osasco', 100.0, 532),
  ('osasco', 100.0, 533),
  ('osasco', 100.0, 562)],
 'valinhos': [('valinhos', 100.0, 193),
  ('valinhos', 100.0, 472),
  ('valinhos', 100.0, 932),
  ('valinhos', 100.0, 1450),
  ('valinhos', 100.0, 2770)],
 'manaus': [('manaus', 100.0, 195),
  ('manaus', 100.0, 909),
  ('manaus', 100.0, 1367),
  ('manaus', 100.0, 2707),
  ('manaus', 100.0, 2945)],
 'cidreira': [('cidreira', 100.0, 196),
  ('cidreira', 100.0, 28071),
  ('cidreira', 100.0, 44219),
  ('cidreira', 100.0, 55818),
  ('cidreira', 100.0, 59834)],
 'santiago': [('santiago', 100.0, 198),
  ('santiago', 100.0, 1271),
  ('santiago', 100.0, 4780),
  ('santiago', 100.0, 5039),
  ('santiago', 100.0, 8628)],
 'sao sepe': [('sao sepe', 100.0, 200),
  ('sao sepe', 100.0, 29658),
  ('sao sepe', 100.0, 35187),
  ('sao sepe', 100.0, 48073),
  ('sao sepe', 100.0, 72159)],
 'alta floresta': [('alta floresta', 100.0, 201),
  ('alta floresta', 100.0, 5458),
  ('alta floresta', 100.0, 15656),
  ('alta floresta', 100.0, 16482),
  ('alta floresta', 100.0, 19459)],
 'jaboatao dos guararapes': [('jaboatao dos guararapes', 100.0, 203),
  ('jaboatao dos guararapes', 100.0, 742),
  ('jaboatao dos guararapes', 100.0, 1204),
  ('jaboatao dos guararapes', 100.0, 1623),
  ('jaboatao dos guararapes', 100.0, 3287)],
 'ibatiba': [('ibatiba', 100.0, 205),
  ('ibatiba', 100.0, 42795),
  ('ibatiba', 100.0, 44355),
  ('ibatiba', 100.0, 75476),
  ('ibatiba', 100.0, 75730)],
 'hortolandia': [('hortolandia', 100.0, 206),
  ('hortolandia', 100.0, 224),
  ('hortolandia', 100.0, 1328),
  ('hortolandia', 100.0, 1674),
  ('hortolandia', 100.0, 3108)],
 'cotia': [('cotia', 100.0, 208),
  ('cotia', 100.0, 409),
  ('cotia', 100.0, 786),
  ('cotia', 100.0, 1039),
  ('cotia', 100.0, 1423)],
 'macae': [('macae', 100.0, 209),
  ('macae', 100.0, 310),
  ('macae', 100.0, 894),
  ('macae', 100.0, 1088),
  ('macae', 100.0, 1526)],
 'saudades': [('saudades', 100.0, 210),
  ('saudades', 100.0, 5229),
  ('saudades', 100.0, 20740),
  ('saudades', 100.0, 29686)],
 'macapa': [('macapa', 100.0, 212),
  ('macapa', 100.0, 2331),
  ('macapa', 100.0, 4907),
  ('macapa', 100.0, 5092),
  ('macapa', 100.0, 7939)],

In [28]:
for df in df_dict:
    print(df)
    print(f"\n{df_dict[df].value_counts()}")

olist_customers_dataset

customer_id                       customer_unique_id                customer_zip_code_prefix  customer_city          customer_state
06b8999e2fba1a1fbc88172c00ba8bc7  861eff4711a542e4b93843c6dd7febb0  14409                     franca                 SP                1
18955e83d337fd6b2def6b18a428ac77  290c77bc529b7ac935b93aa66c333dc3  9790                      sao bernardo do campo  SP                1
4e7b3e00288586ebd08712fdd0374a03  060e732b5b29e8181a18229c7b0b2b5e  1151                      sao paulo              SP                1
b2b6027bc5c5109e529d4dc6358b12c3  259dac757896d24d7702b9acbbff3f3c  8775                      mogi das cruzes        SP                1
4f2d8ab171c80ec8364f7c12e35b23ad  345ecd01c38d18a9036ed96c73b8d066  13056                     campinas               SP                1
                                                                                                                                      ..
17ddf5dd5d51696bb3d7c6291687be6f  1a29b476fee25c95fbafc67c5ac95cf8  3937                      sao paulo              SP                1
e7b71a9017aa05c9a7fd292d714858e8  d52a67c98be1cf6a5c84435bd38d095d  6764                      taboao da serra        SP                1
5e28dfe12db7fb50a4b2f691faecea5e  e9f50caf99f032f0bf3c55141f019d99  60115                     fortaleza              CE                1
56b18e2166679b8a959d72dd06da27f9  73c2643a0a458b49f58cea58833b192e  92120                     canoas                 RS                1
274fa6071e5e17fe303b9748641082c8  84732c5050c01db9b23e19ba39899398  6703                      cotia                  SP                1
Name: count, Length: 99441, dtype: int64
olist_geolocation_dataset

geolocation_zip_code_prefix  geolocation_lat  geolocation_lng  geolocation_city  geolocation_state
88220                        -27.102099       -48.629613       itapema           SC                   314
6414                         -23.495901       -46.874687       barueri           SP                   189
                             -23.490618       -46.869004       barueri           SP                   127
5145                         -23.506049       -46.717377       sao paulo         SP                   126
22620                        -23.005514       -43.375964       rio de janeiro    RJ                   102
                                                                                                     ...
99965                        -28.180655       -52.034367       agua santa        RS                     1
99950                        -28.072188       -52.011272       tapejara          RS                     1
                             -28.068864       -52.012964       tapejara          RS                     1
                             -28.068639       -52.010705       tapejara          RS                     1
99980                        -28.388932       -51.846871       david canabarro   RS                     1
Name: count, Length: 738332, dtype: int64
olist_orders_dataset

order_id                          customer_id                       order_status  order_purchase_timestamp  order_approved_at    order_delivered_carrier_date  order_delivered_customer_date  order_estimated_delivery_date
e481f51cbdc54678b7cc49136f2d6af7  9ef432eb6251297304e76186b10a928d  delivered     2017-10-02 10:56:33       2017-10-02 11:07:15  2017-10-04 19:55:00           2017-10-10 21:25:13            2017-10-18 00:00:00              1
53cdb2fc8bc7dce0b6741e2150273451  b0830fb4747a6c6d20dea0b8c802d7ef  delivered     2018-07-24 20:41:37       2018-07-26 03:24:27  2018-07-26 14:31:00           2018-08-07 15:27:45            2018-08-13 00:00:00              1
47770eb9100c2d0c44946d9cf07ec65d  41ce2a54c0b03bf3443c3d931a367089  delivered     2018-08-08 08:38:49       2018-08-08 08:55:23  2018-08-08 13:50:00           2018-08-17 18:06:29            2018-09-04 00:00:00              1
949d5b44dbf5de918fe9c16f97b45f8a  f88197465ea7920adcdbec7375364d82  delivered     2017-11-18 19:28:06       2017-11-18 19:45:59  2017-11-22 13:39:59           2017-12-02 00:28:42            2017-12-15 00:00:00              1
ad21c59c0840e6cb83a9ceb5573f8159  8ab97904e6daea8866dbdbc4fb7aad2c  delivered     2018-02-13 21:18:39       2018-02-13 22:20:29  2018-02-14 19:46:34           2018-02-16 18:17:02            2018-02-26 00:00:00              1
                                                                                                                                                                                                                              ..
9c5dedf39a927c1b2549525ed64a053c  39bd1228ee8140590ac3aca26f2dfe00  delivered     2017-03-09 09:54:05       2017-03-09 09:54:05  2017-03-10 11:18:03           2017-03-17 15:08:01            2017-03-28 00:00:00              1
63943bddc261676b46f01ca7ac2f7bd8  1fca14ff2861355f6e5f14306ff977a7  delivered     2018-02-06 12:58:58       2018-02-06 13:10:37  2018-02-07 23:22:42           2018-02-28 17:37:56            2018-03-02 00:00:00              1
83c1379a015df1e13d02aae0204711ab  1aa71eb042121263aafbe80c1b562c9c  delivered     2017-08-27 14:46:43       2017-08-27 15:04:16  2017-08-28 20:52:26           2017-09-21 11:24:17            2017-09-27 00:00:00              1
11c177c8e97725db2631073c19f07b62  b331b74b18dc79bcdf6532d51e1637c1  delivered     2018-01-08 21:28:27       2018-01-08 21:36:21  2018-01-12 15:35:03           2018-01-25 23:32:54            2018-02-15 00:00:00              1
66dea50a8b16d9b4dee7af250b4be1a5  edb027a75a1449115f6b43211ae02a24  delivered     2018-03-08 20:57:30       2018-03-09 11:20:28  2018-03-09 22:11:59           2018-03-16 13:08:30            2018-04-03 00:00:00              1
Name: count, Length: 96461, dtype: int64
olist_order_items_dataset

order_id                          order_item_id  product_id                        seller_id                         shipping_limit_date  price   freight_value
00010242fe8c5a6d1ba2dd792cb16214  1              4244733e06e7ecb4970a6e2683c13e61  48436dade18ac8b2bce089ec2a041202  2017-09-19 09:45:35  58.90   13.29            1
00018f77f2f0320c557190d7a144bdd3  1              e5f2d52b802189ee658865ca93d83a8f  dd7ddc04e1b6c2c614352b383efe2d36  2017-05-03 11:05:13  239.90  19.93            1
000229ec398224ef6ca0657da4fc703e  1              c777355d18b72b67abbeef9df44fd0fd  5b51032eddd242adc84c38acab88f23d  2018-01-18 14:48:30  199.00  17.87            1
00024acbcdf0a6daa1e931b038114c75  1              7634da152a4610f1595efa32f14722fc  9d7a1d34a5052409006425275ba1c2b4  2018-08-15 10:10:18  12.99   12.79            1
00042b26cf59d7ce69dfabb4e55b4fd9  1              ac6c3623068f30de03045865e4e10089  df560393f3a51e74553ab94004ba5c87  2017-02-13 13:57:51  199.90  18.14            1
                                                                                                                                                                  ..
fffc94f6ce00a00581880bf54a75a037  1              4aa6014eceb682077f9dc4bffebc05b0  b8bc237ba3788b23da09c0f1f3a3288c  2018-05-02 04:11:01  299.99  43.41            1
fffcd46ef2263f404302a634eb57f7eb  1              32e07fd915822b0765e448c4dd74c828  f3c38ab652836d21de61fb8314b69182  2018-07-20 04:31:48  350.00  36.53            1
fffce4705a9662cd70adb13d4a31832d  1              72a30483855e2eafc67aee5dc2560482  c3cfdc648177fdbbbb35635a37472c53  2017-10-30 17:14:25  99.90   16.95            1
fffe18544ffabc95dfada21779c9644f  1              9c422a519119dcad7575db5af1ba540e  2b3e4a2a3ea8e01938cabda2a3e5cc79  2017-08-21 00:04:32  55.99   8.72             1
fffe41c64501cc87c801fd61db3f6244  1              350688d9dc1e75ff97be326363655e01  f7ccf836d21b2fb1de37564105216cc1  2018-06-12 17:10:13  43.00   12.79            1
Name: count, Length: 112650, dtype: int64
olist_order_payments_dataset

order_id                          payment_sequential  payment_type  payment_installments  payment_value
b81ef226f3fe1789b1e8b2acac839d17  1                   credit_card   8                     99.33            1
a9810da82917af2d9aefd1278f1dcfa0  1                   credit_card   1                     24.39            1
25e8ea4e93396b6fa0d3dd708e76c1bd  1                   credit_card   1                     65.71            1
ba78997921bbcdc1373bb41e913ab953  1                   credit_card   8                     107.78           1
42fdf880ba16b47b59251dd489d4441a  1                   credit_card   2                     128.45           1
                                                                                                          ..
0406037ad97740d563a178ecc7a2075c  1                   boleto        1                     363.31           1
7b905861d7c825891d6347454ea7863f  1                   credit_card   2                     96.80            1
32609bbb3dd69b3c066a6860554a77bf  1                   credit_card   1                     47.77            1
b8b61059626efa996a60be9bb9320e10  1                   credit_card   5                     369.54           1
28bbae6599b09d39ca406b747b6632b1  1                   boleto        1                     191.58           1
Name: count, Length: 103886, dtype: int64
olist_order_reviews_dataset

review_id                         order_id                          review_score  review_comment_title       review_comment_message                                                                                                                                                          review_creation_date  review_answer_timestamp
8670d52e15e00043ae7de4c01cc2fe06  b9bf720beb4ab3728760088589c62129  4             recomendo                  aparelho eficiente. no site a marca do aparelho esta impresso como 3desinfector e ao chegar esta com outro nome...atualizar com a marca correta uma vez que é o mesmo aparelho  2018-05-22 00:00:00   2018-05-23 16:45:47        1
3948b09f7c818e2d86c9a546758b2335  e51478e7e277a83743b6f9991dbfa3fb  5             Super recomendo            Vendedor confiável, produto ok e entrega antes do prazo.                                                                                                                        2018-05-23 00:00:00   2018-05-24 03:00:01        1
373cbeecea8286a2b66c97b1b157ec46  583174fbe37d3d5f0d6661be3aad1786  1             Não chegou meu produto     Péssimo                                                                                                                                                                         2018-08-15 00:00:00   2018-08-15 04:10:37        1
d21bbc789670eab777d27372ab9094cc  4fc44d78867142c627497b60a7e0228a  5             Ótimo                      Loja nota 10                                                                                                                                                                    2018-07-10 00:00:00   2018-07-11 14:10:25        1
c92cdd7dd544a01aa35137f901669cdf  37e7875cdce5a9e5b3a692971f370151  4             Muito bom.                 Recebi exatamente o que esperava. As demais encomendas de outros vendedores atrasaram, mas esta chegou no prazo.                                                                2018-06-07 00:00:00   2018-06-09 18:44:02        1
                                                                                                                                                                                                                                                                                                                                             ..
47e0954e156dac6512c25c6d2ecc1c66  16cbf959cfdb88c47ee2a29303547ec2  5             Nota máxima!               Muito obrigado,\r\n\r\nExcelente atendimento,baratheon e fornecedor targaryen .\r\nVoltarei sempre ao baratheon. \r\nAtenciosamente,\r\nFernando Antonio Polycarpo Gomes.       2018-05-22 00:00:00   2018-05-23 00:51:43        1
0e7bc73fde6782891898ea71443f9904  bd78f91afbb1ecbc6124974c5e813043  4             👍                          Aprovado!                                                                                                                                                                       2018-07-04 00:00:00   2018-07-05 00:25:13        1
58be140ccdc12e8908ff7fd2ba5c7cb0  0ebf8e35b9807ee2d717922d5663ccdb  5             muito bom produto          Ficamos muito satisfeitos com o produto, atende às nossas necessidades com muita facilidade. Recomendo!                                                                         2018-06-30 00:00:00   2018-07-02 23:09:35        1
51de4e06a6b701cb2be47ea0e689437b  b7467ae483dbe956fe9acdf0b1e6e3f4  3             Não foi entregue o pedido  Bom dia \r\nDas 6 unidades compradas só recebi 4 unidades, estou aguardando as demais                                                                                           2018-06-05 00:00:00   2018-06-06 10:52:19        1
2ee221b28e5b6fceffac59487ed39348  f2d12dd37eaef72ed7b1186b2edefbcd  2             Foto enganosa              Foto muito diferente principalmente a graninha sintética muito rala...diferente da foto                                                                                         2018-03-28 00:00:00   2018-05-25 01:23:26        1
Name: count, Length: 9839, dtype: int64
olist_products_dataset

product_id                        product_category_name              product_name_lenght  product_description_lenght  product_photos_qty  product_weight_g  product_length_cm  product_height_cm  product_width_cm
1e9e8ef04dbcff4541ed26657ea517e5  perfumaria                         40.0                 287.0                       1.0                 225.0             16.0               10.0               14.0                1
3aa071139cb16b67ca9e5dea641aaa2f  artes                              44.0                 276.0                       1.0                 1000.0            30.0               18.0               20.0                1
96bd76ec8810374ed1b65e291975717f  esporte_lazer                      46.0                 250.0                       1.0                 154.0             18.0               9.0                15.0                1
cef67bcfe19066a932b7673e239eb23d  bebes                              27.0                 261.0                       1.0                 371.0             26.0               4.0                26.0                1
9dc1a7de274444849c219cff195d0b71  utilidades_domesticas              37.0                 402.0                       4.0                 625.0             20.0               17.0               13.0                1
                                                                                                                                                                                                                     ..
a0b7d5a992ccda646f2d34e418fff5a0  moveis_decoracao                   45.0                 67.0                        2.0                 12300.0           40.0               40.0               40.0                1
bf4538d88321d0fd4412a93c974510e6  construcao_ferramentas_iluminacao  41.0                 971.0                       1.0                 1700.0            16.0               19.0               16.0                1
9a7c6041fa9592d9d9ef6cfe62a71f8c  cama_mesa_banho                    50.0                 799.0                       1.0                 1400.0            27.0               7.0                27.0                1
83808703fc0706a22e264b9d75f04a2e  informatica_acessorios             60.0                 156.0                       2.0                 700.0             31.0               13.0               20.0                1
106392145fca363410d287a815be6de4  cama_mesa_banho                    58.0                 309.0                       1.0                 2083.0            12.0               2.0                7.0                 1
Name: count, Length: 32340, dtype: int64
olist_sellers_dataset

seller_id                         seller_zip_code_prefix  seller_city        seller_state
3442f8959a84dea7ee197c632cb2df15  13023                   campinas           SP              1
d1b65fc7debc3361ea86b5f14c68d2e2  13844                   mogi guacu         SP              1
ce3ad9de960102d0677a81f5d0bb7b2d  20031                   rio de janeiro     RJ              1
c0f3eea2e14555b6faeea3dd58c1b1c3  4195                    sao paulo          SP              1
51a04a8a6bdcb23deccc82b0b80742cf  12914                   braganca paulista  SP              1
                                                                                            ..
98dddbc4601dd4443ca174359b237166  87111                   sarandi            PR              1
f8201cab383e484733266d1906e2fdfa  88137                   palhoca            SC              1
74871d19219c7d518d0090283e03c137  4650                    sao paulo          SP              1
e603cf3fec55f8697c9059638d6c8eb5  96080                   pelotas            RS              1
9e25199f6ef7e7c347120ff175652c3b  12051                   taubate            SP              1
Name: count, Length: 3095, dtype: int64
product_category_name_translation

product_category_name          product_category_name_english
beleza_saude                   health_beauty                    1
informatica_acessorios         computers_accessories            1
automotivo                     auto                             1
cama_mesa_banho                bed_bath_table                   1
moveis_decoracao               furniture_decor                  1
                                                               ..
flores                         flowers                          1
artes_e_artesanato             arts_and_craftmanship            1
fraldas_higiene                diapers_and_hygiene              1
fashion_roupa_infanto_juvenil  fashion_childrens_clothes        1
seguros_e_servicos             security_and_services            1
Name: count, Length: 71, dtype: int64

In [29]:
for name, df in df_dict.items():
    print(f"\n===== {name} =====")
    
    categorical_cols = df.select_dtypes(include="object").columns
    
    for col in categorical_cols:
        print(f"\n--- {col} ---")
        print(df[col].value_counts(dropna=False))

===== olist_customers_dataset =====

--- customer_id ---

C:\Users\DELL\AppData\Local\Temp\ipykernel_22584\1012650061.py:4: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = df.select_dtypes(include="object").columns

customer_id
06b8999e2fba1a1fbc88172c00ba8bc7    1
18955e83d337fd6b2def6b18a428ac77    1
4e7b3e00288586ebd08712fdd0374a03    1
b2b6027bc5c5109e529d4dc6358b12c3    1
4f2d8ab171c80ec8364f7c12e35b23ad    1
                                   ..
17ddf5dd5d51696bb3d7c6291687be6f    1
e7b71a9017aa05c9a7fd292d714858e8    1
5e28dfe12db7fb50a4b2f691faecea5e    1
56b18e2166679b8a959d72dd06da27f9    1
274fa6071e5e17fe303b9748641082c8    1
Name: count, Length: 99441, dtype: int64

--- customer_unique_id ---
customer_unique_id
8d50f5eadf50201ccdcedfb9e2ac8455    17
3e43e6105506432c953e165fb2acf44c     9
1b6c7548a2a1f9037c1fd3ddfed95f33     7
6469f99c1f9dfae7733b25662e7f1782     7
ca77025e7201e3b30c44b472ff346268     7
                                    ..
1a29b476fee25c95fbafc67c5ac95cf8     1
d52a67c98be1cf6a5c84435bd38d095d     1
e9f50caf99f032f0bf3c55141f019d99     1
73c2643a0a458b49f58cea58833b192e     1
84732c5050c01db9b23e19ba39899398     1
Name: count, Length: 96096, dtype: int64

--- customer_city ---
customer_city
sao paulo              15540
rio de janeiro          6882
belo horizonte          2773
brasilia                2131
curitiba                1521
                       ...
siriji                     1
natividade da serra        1
monte bonito               1
sao rafael                 1
eugenio de castro          1
Name: count, Length: 4119, dtype: int64

--- customer_state ---
customer_state
SP    41746
RJ    12852
MG    11635
RS     5466
PR     5045
SC     3637
BA     3380
DF     2140
ES     2033
GO     2020
PE     1652
CE     1336
PA      975
MT      907
MA      747
MS      715
PB      536
PI      495
RN      485
AL      413
SE      350
TO      280
RO      253
AM      148
AC       81
AP       68
RR       46
Name: count, dtype: int64

===== olist_geolocation_dataset =====

--- geolocation_city ---

C:\Users\DELL\AppData\Local\Temp\ipykernel_22584\1012650061.py:4: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = df.select_dtypes(include="object").columns
C:\Users\DELL\AppData\Local\Temp\ipykernel_22584\1012650061.py:4: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = df.select_dtypes(include="object").columns

geolocation_city
sao paulo                     135800
rio de janeiro                 62151
belo horizonte                 27805
são paulo                      24918
curitiba                       16593
                               ...
são josé do herval                 1
almirante tamandaré do sul         1
são valentim                       1
três arroios                       1
ciríaco                            1
Name: count, Length: 8011, dtype: int64

--- geolocation_state ---
geolocation_state
SP    404268
MG    126336
RJ    121169
RS     61851
PR     57859
SC     38328
BA     36045
GO     20139
ES     16748
PE     16432
DF     12986
MT     12031
CE     11674
PA     10853
MS     10431
MA      7853
PB      5538
RN      5041
PI      4549
AL      4183
TO      3576
SE      3563
RO      3478
AM      2432
AC      1301
AP       853
RR       646
Name: count, dtype: int64

===== olist_orders_dataset =====

--- order_id ---
order_id
e481f51cbdc54678b7cc49136f2d6af7    1
53cdb2fc8bc7dce0b6741e2150273451    1
47770eb9100c2d0c44946d9cf07ec65d    1
949d5b44dbf5de918fe9c16f97b45f8a    1
ad21c59c0840e6cb83a9ceb5573f8159    1
                                   ..
9c5dedf39a927c1b2549525ed64a053c    1
63943bddc261676b46f01ca7ac2f7bd8    1
83c1379a015df1e13d02aae0204711ab    1
11c177c8e97725db2631073c19f07b62    1
66dea50a8b16d9b4dee7af250b4be1a5    1
Name: count, Length: 99441, dtype: int64

--- customer_id ---
customer_id
9ef432eb6251297304e76186b10a928d    1
b0830fb4747a6c6d20dea0b8c802d7ef    1
41ce2a54c0b03bf3443c3d931a367089    1
f88197465ea7920adcdbec7375364d82    1
8ab97904e6daea8866dbdbc4fb7aad2c    1
                                   ..
39bd1228ee8140590ac3aca26f2dfe00    1
1fca14ff2861355f6e5f14306ff977a7    1
1aa71eb042121263aafbe80c1b562c9c    1
b331b74b18dc79bcdf6532d51e1637c1    1
edb027a75a1449115f6b43211ae02a24    1
Name: count, Length: 99441, dtype: int64

--- order_status ---
order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

--- order_purchase_timestamp ---
order_purchase_timestamp
2018-03-31 15:08:21    3
2017-11-20 10:59:08    3
2018-08-02 12:06:09    3
2018-08-02 12:05:26    3
2018-02-19 15:37:47    3
                      ..
2017-03-09 09:54:05    1
2018-02-06 12:58:58    1
2017-08-27 14:46:43    1
2018-01-08 21:28:27    1
2018-03-08 20:57:30    1
Name: count, Length: 98875, dtype: int64

--- order_approved_at ---
order_approved_at
NaN                    160
2018-02-27 04:31:10      9
2017-11-07 07:30:38      7
2018-02-06 05:31:52      7
2018-07-05 16:33:01      7
                      ...
2017-03-09 09:54:05      1
2018-02-06 13:10:37      1
2017-08-27 15:04:16      1
2018-01-08 21:36:21      1
2018-03-09 11:20:28      1
Name: count, Length: 90734, dtype: int64

--- order_delivered_carrier_date ---
order_delivered_carrier_date
NaN                    1783
2018-05-09 15:48:00      47
2018-05-10 18:29:00      32
2018-05-07 12:31:00      21
2018-07-24 16:07:00      16
                       ...
2017-03-10 11:18:03       1
2018-02-07 23:22:42       1
2017-08-28 20:52:26       1
2018-01-12 15:35:03       1
2018-03-09 22:11:59       1
Name: count, Length: 81019, dtype: int64

--- order_delivered_customer_date ---
order_delivered_customer_date
NaN                    2965
2018-05-14 20:02:44       3
2016-10-27 17:32:07       3
2018-05-08 23:38:46       3
2018-07-24 21:36:42       3
                       ...
2017-03-06 11:08:08       1
2018-02-28 17:37:56       1
2017-09-21 11:24:17       1
2018-01-25 23:32:54       1
2018-03-16 13:08:30       1
Name: count, Length: 95665, dtype: int64

--- order_estimated_delivery_date ---
order_estimated_delivery_date
2017-12-20 00:00:00    522
2018-03-12 00:00:00    516
2018-03-13 00:00:00    513
2018-05-29 00:00:00    513
2018-02-14 00:00:00    507
                      ...
2016-12-23 00:00:00      1
2017-01-11 00:00:00      1
2016-10-25 00:00:00      1
2018-07-10 00:00:00      1
2016-10-27 00:00:00      1
Name: count, Length: 459, dtype: int64

===== olist_order_items_dataset =====

--- order_id ---
order_id
8272b63d03f5f79c56e9e4120aec44ef    21
1b15974a0141d54e36626dca3fdc731a    20
ab14fdcfbe524636d65ee38360e22ce8    20
428a2f660dc84138d969ccd69a0ab6d5    15
9ef13efd6949e4573a18964dd1bbe7f5    15
                                    ..
fffc94f6ce00a00581880bf54a75a037     1
fffcd46ef2263f404302a634eb57f7eb     1
fffce4705a9662cd70adb13d4a31832d     1
fffe18544ffabc95dfada21779c9644f     1
fffe41c64501cc87c801fd61db3f6244     1
Name: count, Length: 98666, dtype: int64

--- product_id ---
product_id
aca2eb7d00ea1a7b8ebd4e68314663af    527
99a4788cb24856965c36a24e339b6058    488
422879e10f46682990de24d770e7f83d    484
389d119b48cf3043d311335e499d9c6b    392
368c6c730842d78016ad823897a372db    388
                                   ...
4cc4d02efc8f249c13355147fb44e34d      1
b10ecf8e33aaaea419a9fa860ea80fb5      1
dd469c03ad67e201bc2179ef077dcd48      1
bbe7651fef80287a816ead73f065fc4b      1
350688d9dc1e75ff97be326363655e01      1
Name: count, Length: 32951, dtype: int64

--- seller_id ---
seller_id
6560211a19b47992c3666cc44a7e94c0    2033
4a3ca9315b744ce9f8e9374361493884    1987
1f50f920176fa81dab994f9023523100    1931
cc419e0650a3c5ba77189a1882b7556a    1775
da8622b14eb17ae2831f4ac5b9dab84a    1551
                                    ...
a1bea9970d8f65b240555f99c2214f7f       1
d1aa1ec0839dcab73a6161130eb1f94a       1
dbc51f5e45d654ecc16cb68e6817ecea       1
3fefda3299e6dfaea3466ef346a3571a       1
80ceebb4ee9b31afb6c6a916a574a1e2       1
Name: count, Length: 3095, dtype: int64

--- shipping_limit_date ---

C:\Users\DELL\AppData\Local\Temp\ipykernel_22584\1012650061.py:4: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = df.select_dtypes(include="object").columns
C:\Users\DELL\AppData\Local\Temp\ipykernel_22584\1012650061.py:4: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = df.select_dtypes(include="object").columns
C:\Users\DELL\AppData\Local\Temp\ipykernel_22584\1012650061.py:4: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = df.select_dtypes(include="object").columns

shipping_limit_date
2018-03-01 02:50:48    21
2017-07-21 18:25:23    21
2017-08-30 14:30:23    20
2017-11-30 10:30:51    15
2017-12-21 02:30:41    15
                       ..
2018-05-02 04:11:01     1
2018-07-20 04:31:48     1
2017-10-30 17:14:25     1
2017-08-21 00:04:32     1
2018-06-12 17:10:13     1
Name: count, Length: 93318, dtype: int64

===== olist_order_payments_dataset =====

--- order_id ---
order_id
fa65dad1b0e818e3ccc5cb0e39231352    29
ccf804e764ed5650cd8759557269dc13    26
285c2e15bebd4ac83635ccc563dc71f4    22
895ab968e7bb0d5659d16cd74cd1650c    21
ee9ca989fc93ba09a6eddc250ce01742    19
                                    ..
0406037ad97740d563a178ecc7a2075c     1
7b905861d7c825891d6347454ea7863f     1
32609bbb3dd69b3c066a6860554a77bf     1
b8b61059626efa996a60be9bb9320e10     1
28bbae6599b09d39ca406b747b6632b1     1
Name: count, Length: 99440, dtype: int64

--- payment_type ---
payment_type
credit_card    76795
boleto         19784
voucher         5775
debit_card      1529
not_defined        3
Name: count, dtype: int64

===== olist_order_reviews_dataset =====

--- review_id ---
review_id
c444278834184f72b1484dfe47de7f97    3
308316408775d1600dad81bd3184556d    3
2d6ac45f859465b5c185274a1c929637    3
3415c9f764e478409e8e0660ae816dd2    3
4219a80ab469e3fc9901437b73da3f75    3
                                   ..
574ed12dd733e5fa530cfd4bbf39d7c9    1
f3897127253a9592a73be9bdfdf4ed7a    1
b3de70c89b1510c4cd3d0649fd302472    1
1adeb9d84d72fe4e337617733eb85149    1
efe49f1d6f951dd88b51e6ccd4cc548f    1
Name: count, Length: 98410, dtype: int64

--- order_id ---
order_id
c88b1d1b157a9999ce368f218a407141    3
df56136b8031ecd28e200bb18e6ddb2e    3
03c939fd7fd3b38f8485a0f95798f1f6    3
8e17072ec97ce29f0e1f111e598b0c85    3
cf73e2cb1f4a9480ed70c154da3d954a    2
                                   ..
2a8c23fee101d4d5662fa670396eb8da    1
22ec9f0669f784db00fa86d035cf8602    1
55d4004744368f5571d1f590031933e4    1
7725825d039fc1f0ceb7635e3f7d9206    1
90531360ecb1eec2a1fbb265a0db0508    1
Name: count, Length: 98673, dtype: int64

--- review_comment_title ---
review_comment_title
NaN                          87656
Recomendo                      423
recomendo                      345
Bom                            293
super recomendo                270
                             ...
Nota máxima!                     1
muito bom produto                1
Não foi entregue o pedido        1
OTIMA EMBALAGEM                  1
Foto enganosa                    1
Name: count, Length: 4528, dtype: int64

--- review_comment_message ---
review_comment_message
NaN                                                                                                                              58247
Muito bom                                                                                                                          230
Bom                                                                                                                                189
muito bom                                                                                                                          122
bom                                                                                                                                107
                                                                                                                                 ...
para este produto recebi de acordo com a compra realizada!                                                                           1
Entregou dentro do prazo. O produto chegou em condições perfeitas. Estou muito satisfeita!                                           1
O produto não foi enviado com NF, não existe venda sem NF, com certeza fico no aguardo do envio da NF podendo ser por e-mail.        1
Excelente mochila, entrega super rápida. Super recomendo essa loja!                                                                  1
meu produto chegou e ja tenho que devolver, pois está com defeito , não segurar carga                                                1
Name: count, Length: 36160, dtype: int64

--- review_creation_date ---
review_creation_date
2017-12-19 00:00:00    463
2018-08-28 00:00:00    452
2017-12-20 00:00:00    440
2018-05-19 00:00:00    434
2018-05-15 00:00:00    425
                      ...
2017-03-13 00:00:00      1
2018-02-13 00:00:00      1
2016-11-15 00:00:00      1
2017-06-05 00:00:00      1
2017-01-04 00:00:00      1
Name: count, Length: 636, dtype: int64

--- review_answer_timestamp ---
review_answer_timestamp
2017-06-15 23:21:05    4
2017-02-14 13:58:48    3
2017-09-11 09:58:09    3
2018-04-07 21:13:05    3
2018-07-31 23:11:57    3
                      ..
2018-07-14 17:18:30    1
2017-12-11 20:06:42    1
2018-03-23 09:10:43    1
2018-07-02 12:59:13    1
2017-07-03 21:01:49    1
Name: count, Length: 98248, dtype: int64

===== olist_products_dataset =====

--- product_id ---
product_id
1e9e8ef04dbcff4541ed26657ea517e5    1
3aa071139cb16b67ca9e5dea641aaa2f    1
96bd76ec8810374ed1b65e291975717f    1
cef67bcfe19066a932b7673e239eb23d    1
9dc1a7de274444849c219cff195d0b71    1
                                   ..
a0b7d5a992ccda646f2d34e418fff5a0    1
bf4538d88321d0fd4412a93c974510e6    1
9a7c6041fa9592d9d9ef6cfe62a71f8c    1
83808703fc0706a22e264b9d75f04a2e    1
106392145fca363410d287a815be6de4    1
Name: count, Length: 32951, dtype: int64

--- product_category_name ---
product_category_name
cama_mesa_banho                  3029
esporte_lazer                    2867
moveis_decoracao                 2657
beleza_saude                     2444
utilidades_domesticas            2335
                                 ...
fashion_roupa_infanto_juvenil       5
casa_conforto_2                     5
pc_gamer                            3
seguros_e_servicos                  2
cds_dvds_musicais                   1
Name: count, Length: 74, dtype: int64

===== olist_sellers_dataset =====

--- seller_id ---
seller_id
3442f8959a84dea7ee197c632cb2df15    1
d1b65fc7debc3361ea86b5f14c68d2e2    1
ce3ad9de960102d0677a81f5d0bb7b2d    1
c0f3eea2e14555b6faeea3dd58c1b1c3    1
51a04a8a6bdcb23deccc82b0b80742cf    1
                                   ..
98dddbc4601dd4443ca174359b237166    1
f8201cab383e484733266d1906e2fdfa    1
74871d19219c7d518d0090283e03c137    1
e603cf3fec55f8697c9059638d6c8eb5    1
9e25199f6ef7e7c347120ff175652c3b    1
Name: count, Length: 3095, dtype: int64

--- seller_city ---
seller_city
sao paulo                 694
curitiba                  127
rio de janeiro             96
belo horizonte             68
ribeirao preto             52
                         ...
aparecida de goiania        1
bandeirantes                1
vitoria de santo antao      1
palotina                    1
leme                        1
Name: count, Length: 611, dtype: int64

--- seller_state ---
seller_state
SP    1849
PR     349
MG     244
SC     190
RJ     171
RS     129
GO      40
DF      30
ES      23
BA      19
CE      13
PE       9
PB       6
RN       5
MS       5
MT       4
RO       2
SE       2
AC       1
PI       1
MA       1
AM       1
PA       1
Name: count, dtype: int64

===== product_category_name_translation =====

--- product_category_name ---
product_category_name
beleza_saude                     1
informatica_acessorios           1
automotivo                       1
cama_mesa_banho                  1
moveis_decoracao                 1
                                ..
flores                           1
artes_e_artesanato               1
fraldas_higiene                  1
fashion_roupa_infanto_juvenil    1
seguros_e_servicos               1
Name: count, Length: 71, dtype: int64

--- product_category_name_english ---
product_category_name_english
health_beauty                1
computers_accessories        1
auto                         1
bed_bath_table               1
furniture_decor              1
                            ..
flowers                      1
arts_and_craftmanship        1
diapers_and_hygiene          1
fashion_childrens_clothes    1
security_and_services        1
Name: count, Length: 71, dtype: int64

C:\Users\DELL\AppData\Local\Temp\ipykernel_22584\1012650061.py:4: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = df.select_dtypes(include="object").columns
C:\Users\DELL\AppData\Local\Temp\ipykernel_22584\1012650061.py:4: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = df.select_dtypes(include="object").columns
C:\Users\DELL\AppData\Local\Temp\ipykernel_22584\1012650061.py:4: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = df.select_dtypes(include="object").columns

In [152]:
missing_summary = {}

for name, df in df_dict.items():
    missing = df.isna().sum()
    missing = missing[missing > 0].sort_values(ascending=False)
    
    missing_summary[name] = missing

    print(f"\n===== {name} =====")
    print(missing)

===== olist_customers_dataset =====
Series([], dtype: int64)

===== olist_geolocation_dataset =====
Series([], dtype: int64)

===== olist_orders_dataset =====
order_delivered_customer_date    2965
order_delivered_carrier_date     1783
order_approved_at                 160
dtype: int64

===== olist_order_items_dataset =====
Series([], dtype: int64)

===== olist_order_payments_dataset =====
Series([], dtype: int64)

===== olist_order_reviews_dataset =====
review_comment_title      87656
review_comment_message    58247
dtype: int64

===== olist_products_dataset =====
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

===== olist_sellers_dataset =====
Series([], dtype: int64)

===== product_category_name_translation =====
Series([], dtype: int64)

In [ ]:
missing_summary = {}

for name, df in df_dict.items():
    missing_values = df.isna().sum()
    missing_values = missing_values[missing_values > 0].sort_values(ascending = False)

    missing_summary[name] = missing_values
    print(f"-- {name} --")
    print(missing_values)

In [ ]:
#duplicate_summary = {}

for name, df in df_dict.items():
    duplicate_values = df.duplicated().sum()F
    #duplicate_values = duplicate_values[duplicate_values>0]#.sort_values(ascending = False)

    #duplicate_summary[name] = duplicated_values
    print(f"-- {name} --")
    print(duplicate_values)

-- olist_customers_dataset --
0
-- olist_geolocation_dataset --
261831
-- olist_orders_dataset --
0
-- olist_order_items_dataset --
0
-- olist_order_payments_dataset --
0
-- olist_order_reviews_dataset --
0
-- olist_products_dataset --
0
-- olist_sellers_dataset --
0
-- product_category_name_translation --
0

In [2]:
for name, df in df_dict:
    df.info()

NameError: name 'df_dict' is not defined

In [165]:
df_dict["olist_geolocation_dataset"].sample(20)
#df_dict["olist_geolocation_dataset"].info()

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
663635,39665,-17.527660,-43.015626,carbonita,MG
949475,91520,-30.067534,-51.172402,porto alegre,RS
371980,17400,-22.207649,-49.652025,garca,SP
184217,7132,-23.432808,-46.513905,guarulhos,SP
755442,64965,-10.139270,-43.944987,avelino lopes,PI
900810,88056,-27.417630,-48.424599,florianópolis,SC
883910,86061,-23.311332,-51.179982,londrina,PR
23190,2273,-23.458877,-46.585741,são paulo,SP
290510,13160,-22.579270,-47.158133,artur nogueira,SP
301521,13387,-22.778818,-47.283488,nova odessa,SP
855699,82300,-25.416926,-49.349574,curitiba,PR
4934,1233,-23.536586,-46.662204,são paulo,SP
814064,76811,-8.803748,-63.863144,porto velho,RO
645722,38400,-18.923048,-48.278366,uberlandia,MG
799911,74643,-16.670631,-49.243555,goiania,GO
250946,11250,-23.843805,-46.140722,bertioga,SP
558450,30820,-19.898769,-44.005415,belo horizonte,MG
351929,15340,-20.856747,-50.262521,nova luzitania,SP
385041,18130,-23.530058,-47.137799,sao roque,SP
712755,52061,-8.034083,-34.917316,recife,PE

In [ ]:
missing_vals = df_dict["olist_orders_dataset"].isna().sum().sort_values(ascending=False)
missing_vals[missing_vals>0]

order_delivered_customer_date    2965
order_delivered_carrier_date     1783
order_approved_at                 160
dtype: int64